export default {
  login: "gvanrossum",
  id: 2894642,
  node_id: "MDQ6VXNlcjI4OTQ2NDI=",
  avatar_url: "https://avatars.githubusercontent.com/u/2894642?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/gvanrossum",
  html_url: "https://github.com/gvanrossum",
  followers_url: "https://api.github.com/users/gvanrossum/followers",
  following_url: "https://api.github.com/users/gvanrossum/following{/other_user}",
  gists_url: "https://api.github.com/users/gvanrossum/gists{/gist_id}",
  starred_url: "https://api.github.com/users/gvanrossum/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/gvanrossum/subscriptions",
  organizations_url: "https://api.github.com/users/gvanrossum/orgs",
  repos_url: "https://api.github.com/users/gvanrossum/repos",
  events_url: "https://api.github.com/users/gvanrossum/events{/privacy}",
  received_events_url: "https://api.github.com/users/gvanrossum/received_events",
  type: "User",
  site_admin: false,
  name: "Guido van Rossum",
  company: "Microsoft",
  blog: "https://python.org/~guido/",
  location: "San Francisco Bay Area",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "gvanrossum",
  public_repos: 22,
  public_gists: 11,
  followers: 15814,
  following: 2,
  created_at: "2012-11-26T18:46:40Z",
  updated_at: "2021-08-19T22:15:36Z"
};